module.exports = {
  SUPPORT_PHONE: process.env.SUPPORT_PHONE || '8502947105',
  JWT_EXPIRES_IN: '7d',
  BCRYPT_ROUNDS: 10,
  RATE_LIMIT_WINDOW_MS: 15 * 60 * 1000,
  RATE_LIMIT_MAX: process.env.NODE_ENV === 'test' ? 10000 : 100,
  DEFAULT_PAGE_SIZE: 12,
  MAX_PAGE_SIZE: 50,
  PLACE_TYPES: ['monument', 'temple', 'dargah', 'church', 'haunted', 'tourism', 'other'],
  FEEDBACK_KINDS: ['general', 'report'],
  ESCALATION_KEYWORDS: [
    'agent',
    'human',
    'talk to someone',
    'complaint',
    'call',
    'representative',
    'customer care',
    'support team',
    'phone',
    'helpline',
  ],
};
