// UI strings as [English, Hindi] tuples. Content strings come from the API (name_en / name_hi).
export const STRINGS = {
  brand: ['Bharat Darshan', 'भारत दर्शन'],
  tagline: ['Explore the heritage and culture of India', 'भारत की विरासत और संस्कृति की खोज करें'],
  heroTitle: ['Discover Incredible India', 'अतुल्य भारत की खोज करें'],
  heroSub: [
    'Rotate the 3D map and click any state to explore its monuments, temples, crafts, traditions and food, in English or Hindi.',
    '3D मानचित्र को घुमाएँ और किसी भी राज्य पर क्लिक कर उसके स्मारक, मंदिर, शिल्प, परंपराएँ और भोजन देखें, अंग्रेज़ी या हिंदी में।',
  ],
  mapHint: ['Drag to rotate, scroll to zoom, click a state to explore', 'घुमाने के लिए खींचें, ज़ूम के लिए स्क्रॉल करें, राज्य पर क्लिक करें'],
  mapAria: ['Interactive map of India: choose a state', 'भारत का इंटरैक्टिव मानचित्र: एक राज्य चुनें'],
  listView: ['List view', 'सूची देखें'],
  mapView: ['3D map', '3D मानचित्र'],
  legendActive: ['Ready to explore', 'देखने के लिए तैयार'],
  legendComingSoon: ['Coming soon', 'जल्द आ रहा है'],
  noWebGL: ['3D is not supported on this device. Pick a state below.', 'इस डिवाइस पर 3D समर्थित नहीं है। नीचे से एक राज्य चुनें।'],
  clickToExplore: ['Click to explore', 'देखने के लिए क्लिक करें'],
  comingSoon: ['Content coming soon', 'सामग्री जल्द आ रही है'],
  searchPlaceholder: ['Search monuments, food, crafts, states...', 'स्मारक, भोजन, शिल्प, राज्य खोजें...'],
  search: ['Search', 'खोजें'],
  surpriseMe: ['Surprise Me', 'कुछ नया दिखाओ'],
  exploreStates: ['Explore states', 'राज्य देखें'],
  featuredStates: ['Start with these states', 'इन राज्यों से शुरू करें'],
  whyTitle: ['One map, all of India', 'एक मानचित्र, पूरा भारत'],
  feature1Title: ['3D interactive map', '3D इंटरैक्टिव मानचित्र'],
  feature1Text: ['Rotate, zoom and click states to travel across India.', 'राज्यों को घुमाएँ, ज़ूम करें और क्लिक कर भारत की यात्रा करें।'],
  feature2Title: ['Bilingual content', 'द्विभाषी सामग्री'],
  feature2Text: ['Every place, craft and dish in simple English and Hindi, with audio narration.', 'हर स्थान, शिल्प और व्यंजन सरल अंग्रेज़ी और हिंदी में, ऑडियो के साथ।'],
  feature3Title: ['Assistant and support', 'सहायक और सहयोग'],
  feature3Text: ['Ask the chat assistant anything, or connect to a human in one tap.', 'चैट सहायक से कुछ भी पूछें, या एक टैप में इंसान से बात करें।'],

  home: ['Home', 'होम'],
  about: ['About', 'हमारे बारे में'],
  feedback: ['Feedback', 'प्रतिक्रिया'],
  login: ['Login', 'लॉगइन'],
  signup: ['Sign up', 'साइन अप'],
  logout: ['Logout', 'लॉगआउट'],
  dashboard: ['Dashboard', 'डैशबोर्ड'],
  menu: ['Menu', 'मेनू'],

  name: ['Name', 'नाम'],
  email: ['Email', 'ईमेल'],
  password: ['Password', 'पासवर्ड'],
  passwordHint: ['At least 8 characters', 'कम से कम 8 अक्षर'],
  loginTitle: ['Welcome back', 'वापसी पर स्वागत है'],
  loginSub: ['Log in to see your saved places.', 'अपने सहेजे स्थान देखने के लिए लॉगइन करें।'],
  signupTitle: ['Create your account', 'अपना खाता बनाएँ'],
  signupSub: ['Save favourite places and track your feedback.', 'पसंदीदा स्थान सहेजें और अपनी प्रतिक्रिया देखें।'],
  noAccount: ["Don't have an account?", 'खाता नहीं है?'],
  haveAccount: ['Already have an account?', 'पहले से खाता है?'],
  submitting: ['Please wait...', 'कृपया प्रतीक्षा करें...'],

  myFavorites: ['My favourite places', 'मेरे पसंदीदा स्थान'],
  noFavorites: ['You have not saved any places yet. Explore the map and tap Save on a place you love.', 'आपने अभी कोई स्थान नहीं सहेजा है। मानचित्र देखें और पसंदीदा स्थान पर सहेजें दबाएँ।'],
  feedbackHistory: ['Your feedback', 'आपकी प्रतिक्रिया'],
  noFeedback: ['No feedback submitted yet.', 'अभी कोई प्रतिक्रिया नहीं दी गई।'],
  welcomeBack: ['Welcome', 'स्वागत है'],
  remove: ['Remove', 'हटाएँ'],

  nothingHere: ['Nothing here yet. Check back soon.', 'यहाँ अभी कुछ नहीं है। जल्द ही देखें।'],
  loading: ['Loading...', 'लोड हो रहा है...'],
  errorGeneric: ['Something went wrong, please try again.', 'कुछ गलत हो गया, कृपया पुनः प्रयास करें।'],
  retry: ['Try again', 'पुनः प्रयास करें'],
  viewAll: ['View all', 'सभी देखें'],
  back: ['Back', 'वापस'],
  backHome: ['Back to home', 'होम पर वापस जाएँ'],
  notFoundTitle: ['Page not found', 'पेज नहीं मिला'],
  notFoundText: ['The page you are looking for does not exist or has moved.', 'आप जिस पेज की तलाश कर रहे हैं वह मौजूद नहीं है।'],

  listen: ['Listen', 'सुनें'],
  stop: ['Stop', 'रोकें'],
  bestTime: ['Best time to visit', 'घूमने का सबसे अच्छा समय'],
  location: ['Location', 'स्थान'],
  openInMaps: ['Open in Google Maps', 'Google Maps में खोलें'],
  saveFav: ['Save to favourites', 'पसंदीदा में सहेजें'],
  removeFav: ['Remove from favourites', 'पसंदीदा से हटाएँ'],
  loginToSave: ['Login to save', 'सहेजने के लिए लॉगइन करें'],
  reportInfo: ['Report incorrect info', 'गलत जानकारी की सूचना दें'],
  moreFrom: ['More from', 'और देखें'],
  views: ['views', 'बार देखा गया'],
  share: ['Share', 'शेयर करें'],
  linkCopied: ['Link copied', 'लिंक कॉपी हो गया'],
  in: ['in', 'में'],

  results: ['results', 'परिणाम'],
  resultsFor: ['Results for', 'के लिए परिणाम'],
  noResults: ['No results found. Try another word.', 'कोई परिणाम नहीं मिला। कोई और शब्द आज़माएँ।'],
  typeToSearch: ['Type something to search.', 'खोजने के लिए कुछ टाइप करें।'],

  feedbackTitle: ['We would love your feedback', 'हमें आपकी प्रतिक्रिया चाहिए'],
  feedbackSub: ['Tell us what you liked and what we can improve.', 'बताएँ आपको क्या पसंद आया और हम क्या सुधार सकते हैं।'],
  reportTitle: ['Report incorrect information', 'गलत जानकारी की सूचना दें'],
  reportSub: ['Tell us what is wrong and we will fix it.', 'बताएँ क्या गलत है और हम इसे ठीक करेंगे।'],
  yourRating: ['Your rating', 'आपकी रेटिंग'],
  yourMessage: ['Your message', 'आपका संदेश'],
  messagePlaceholder: ['Write your thoughts here...', 'अपने विचार यहाँ लिखें...'],
  submit: ['Submit', 'जमा करें'],
  thankYou: ['Thank you!', 'धन्यवाद!'],
  feedbackReceived: ['Your feedback has been received. It helps us make Bharat Darshan better.', 'आपकी प्रतिक्रिया मिल गई है। यह भारत दर्शन को बेहतर बनाने में मदद करती है।'],
  sendAnother: ['Send another', 'एक और भेजें'],
  reportingAbout: ['Reporting about', 'इसके बारे में सूचना'],

  chatTitle: ['Bharat Darshan Assistant', 'भारत दर्शन सहायक'],
  chatWelcome: [
    "Hi! I'm your Bharat Darshan assistant. Ask me about monuments, food, culture, or say 'talk to agent' to reach our team.",
    'नमस्ते! मैं आपका भारत दर्शन सहायक हूँ। मुझसे स्मारकों, भोजन, संस्कृति के बारे में पूछें, या हमारी टीम से बात करने के लिए "talk to agent" कहें।',
  ],
  chatPlaceholder: ['Type your question...', 'अपना प्रश्न लिखें...'],
  chatOpen: ['Open chat assistant', 'चैट सहायक खोलें'],
  chatClose: ['Close chat', 'चैट बंद करें'],
  send: ['Send', 'भेजें'],
  quick1: ['Famous monuments', 'प्रसिद्ध स्मारक'],
  quick2: ['Food of Rajasthan', 'राजस्थान का भोजन'],
  quick3: ['Talk to agent', 'एजेंट से बात करें'],
  connectCare: ['Connect to Customer Care', 'ग्राहक सेवा से जुड़ें'],
  call: ['Call', 'कॉल करें'],
  chatError: ['Could not send. Tap to retry.', 'भेज नहीं सके। पुनः प्रयास के लिए टैप करें।'],

  customerCare: ['Customer care', 'ग्राहक सेवा'],
  quickLinks: ['Quick links', 'त्वरित लिंक'],
  madeFor: ['Made for Smart India Hackathon 2026, Problem Statement 26197', 'स्मार्ट इंडिया हैकाथॉन 2026, समस्या कथन 26197 के लिए बनाया गया'],
  aboutTitle: ['About Bharat Darshan', 'भारत दर्शन के बारे में'],
  aboutText1: [
    'Bharat Darshan is a 3D interactive heritage map of India built for Smart India Hackathon 2026 (Problem Statement 26197, AICTE, Heritage & Culture theme). It brings monuments, temples, dargahs, churches, haunted places, crafts, traditions and food of every state to one place.',
    'भारत दर्शन स्मार्ट इंडिया हैकाथॉन 2026 (समस्या कथन 26197, AICTE, विरासत और संस्कृति) के लिए बनाया गया भारत का 3D इंटरैक्टिव विरासत मानचित्र है। यह हर राज्य के स्मारक, मंदिर, दरगाह, गिरजाघर, रहस्यमयी स्थान, शिल्प, परंपराएँ और भोजन को एक जगह लाता है।',
  ],
  aboutText2: [
    'Content is written in simple English and Hindi so students, travellers and families can all enjoy it. Every page can be read aloud, and our assistant is available around the clock with a one-tap connection to a human.',
    'सामग्री सरल अंग्रेज़ी और हिंदी में लिखी गई है ताकि विद्यार्थी, यात्री और परिवार सभी इसका आनंद ले सकें। हर पेज को सुना जा सकता है, और हमारा सहायक हर समय उपलब्ध है, एक टैप में इंसान से जुड़ने के साथ।',
  ],
  contactTitle: ['Contact us', 'संपर्क करें'],
  contactText: ['Our support team is a call away.', 'हमारी सहायता टीम एक कॉल की दूरी पर है।'],
  techTitle: ['Built with', 'इससे बनाया गया'],

  // Layout / a11y
  skipToContent: ['Skip to content', 'मुख्य सामग्री पर जाएँ'],

  // Auth forms
  confirmPassword: ['Confirm password', 'पासवर्ड की पुष्टि करें'],
  show: ['Show', 'दिखाएँ'],
  hide: ['Hide', 'छिपाएँ'],
  showPassword: ['Show password', 'पासवर्ड दिखाएँ'],
  hidePassword: ['Hide password', 'पासवर्ड छिपाएँ'],
  invalidEmail: ['Please enter a valid email address', 'कृपया एक मान्य ईमेल पता दर्ज करें'],
  passwordRequired: ['Password is required', 'पासवर्ड आवश्यक है'],
  passwordTooShort: ['Password must be at least 8 characters', 'पासवर्ड कम से कम 8 अक्षरों का होना चाहिए'],
  passwordsMismatch: ['Passwords do not match', 'पासवर्ड मेल नहीं खाते'],
  nameTooShort: ['Name must be 2 to 60 characters', 'नाम 2 से 60 अक्षरों का होना चाहिए'],
  errInvalidCredentials: ['Incorrect email or password.', 'ईमेल या पासवर्ड गलत है।'],
  errEmailInUse: ['This email is already registered. Try logging in instead.', 'यह ईमेल पहले से पंजीकृत है। इसके बजाय लॉगइन करें।'],

  // Admin panel
  adminPanel: ['Admin panel', 'व्यवस्थापक पैनल'],
  adminSub: ['Add or edit heritage content without redeploying.', 'बिना पुनः डिप्लॉय किए विरासत सामग्री जोड़ें या बदलें।'],
  addNew: ['Add new', 'नया जोड़ें'],
  edit: ['Edit', 'बदलें'],
  delete: ['Delete', 'हटाएँ'],
  save: ['Save', 'सहेजें'],
  cancel: ['Cancel', 'रद्द करें'],
  view: ['View', 'देखें'],
  feedbackInbox: ['Feedback inbox', 'प्रतिक्रिया इनबॉक्स'],
  allStates: ['All states', 'सभी राज्य'],
  allKinds: ['All kinds', 'सभी प्रकार'],
  anonymous: ['Anonymous', 'अनाम'],
  confirmDelete: ['Delete this item? This cannot be undone.', 'यह आइटम हटाएँ? इसे पूर्ववत नहीं किया जा सकता।'],
  saved: ['Saved', 'सहेजा गया'],
  deleted: ['Deleted', 'हटाया गया'],
  previous: ['Previous', 'पिछला'],
  next: ['Next', 'अगला'],
  page: ['Page', 'पेज'],
  total: ['total', 'कुल'],

  // Dashboard
  memberSince: ['Member since', 'सदस्य बने'],
  admin: ['Admin', 'व्यवस्थापक'],
  savedPlaces: ['Saved places', 'सहेजे स्थान'],
  exploreMap: ['Explore the map', 'मानचित्र देखें'],
  giveFeedback: ['Give feedback', 'प्रतिक्रिया दें'],
  general: ['General', 'सामान्य'],
  report: ['Report', 'सूचना'],

  // Feedback
  star: ['star', 'स्टार'],
  stars: ['stars', 'स्टार'],
  rating1: ['Poor', 'खराब'],
  rating2: ['Fair', 'ठीक-ठाक'],
  rating3: ['Good', 'अच्छा'],
  rating4: ['Very good', 'बहुत अच्छा'],
  rating5: ['Excellent', 'उत्कृष्ट'],
  ratingRequired: ['Please choose a rating', 'कृपया रेटिंग चुनें'],
  messageTooShort: ['Message must be at least 3 characters', 'संदेश कम से कम 3 अक्षरों का होना चाहिए'],
  characters: ['characters', 'अक्षर'],
  submittingAs: ['Submitting as', 'इस नाम से जमा हो रहा है'],
  anonymousNote: ['You are not logged in, so this will be sent anonymously.', 'आप लॉगइन नहीं हैं, इसलिए यह अनाम रूप से भेजा जाएगा।'],
  loginToTrack: ['Login to keep a history of your feedback.', 'अपनी प्रतिक्रिया का इतिहास रखने के लिए लॉगइन करें।'],
  viewPlace: ['View place', 'स्थान देखें'],
  switchToGeneral: ['Send general feedback instead', 'इसके बजाय सामान्य प्रतिक्रिया दें'],

  // About
  problemStatement: ['Problem Statement', 'समस्या कथन'],
  whatYouFind: ['What you will find', 'आपको क्या मिलेगा'],
  howItWorks: ['How it works', 'यह कैसे काम करता है'],
  step1: ['Pick a state on the 3D map', '3D मानचित्र पर एक राज्य चुनें'],
  step2: ['Browse its monuments, temples, crafts, traditions and food', 'उसके स्मारक, मंदिर, शिल्प, परंपराएँ और भोजन देखें'],
  step3: ['Read or listen in English or Hindi, and save what you love', 'अंग्रेज़ी या हिंदी में पढ़ें या सुनें, और पसंदीदा सहेजें'],
  statesCovered: ['States you can explore today', 'आज आप ये राज्य देख सकते हैं'],
  askAssistant: ['Or ask the chat assistant at the bottom right of any page.', 'या किसी भी पेज के नीचे दाईं ओर चैट सहायक से पूछें।'],
};
